import { ApiProperty } from '@nestjs/swagger';
import {
  BeforeInsert,
  BeforeUpdate,
  Column,
  Entity,
  PrimaryGeneratedColumn,
} from 'typeorm';

@Entity({ name: 'user' })
export class User {
  @ApiProperty({
    example: 1,
    description: 'Autogenerated user code',
    uniqueItems: true,
  })
  @PrimaryGeneratedColumn('increment')
  code: number;

  @ApiProperty({ example: 'Customer Test', description: 'Customer full name' })
  @Column('varchar')
  fullname: string;

  @ApiProperty({ example: 'customer@example.com', uniqueItems: true })
  @Column('varchar', { unique: true })
  email: string;

  @Column('varchar', { nullable: true })
  password: string;

  @ApiProperty({ example: true })
  @Column('bool', { default: true })
  isActive: boolean;

  @ApiProperty({ example: ['user'], description: 'User roles' })
  @Column('text', { array: true, default: ['user'] })
  roles: string[];

  @BeforeInsert()
  @BeforeUpdate()
  normalizeEmail() {
    if (this.email) {
      this.email = this.email.toLowerCase().trim();
    }
  }
}
